apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: global-project
  namespace: argocd
spec:
  description: "Global project for local multi-cluster testing"
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
