# values.yaml — minimal test configuration
namespaceOverride: "monitoring"

crds:
  enabled: true

alertmanager:
  enabled: true
  service:
    type: NodePort
    nodePort: 30903

grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin
  service:
    type: NodePort
    nodePort: 30300
  ingress:
    enabled: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    retention: 12h
    scrapeInterval: 30s
    enableAdminAPI: true
  service:
    type: NodePort
    nodePort: 30900

defaultRules:
  create: true
  rules:
    alertmanager: true
    node: true
    prometheus: true

kubeApiServer:
  enabled: true
kubelet:
  enabled: true
  serviceMonitor:
    https: true
kubeControllerManager:
  enabled: true
coreDns:
  enabled: true
kubeProxy:
  enabled: true
kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: true
