apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: argocd.argoproj.io/secret-type
              operator: In
              values: ["cluster"]
            - key: name
              operator: NotIn
              values: ["in-cluster", "mgmt"]   # 🔹 exclude mgmt cluster (and in-cluster)
  template:
    metadata:
      name: '{{name}}-monitoring'
    spec:
      project: global-project
      source:
        repoURL: https://github.com/IronPhysique/argocd-devops.git
        targetRevision: HEAD
        path: ../charts/kube-prometheus-stack    
        helm:
          releaseName: kube-prometheus-stack
      destination:
        server: '{{server}}'
        namespace: kube-prometheus-stack
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
